trigger:
- master

jobs:

- job: Pipeline
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script:
      docker run
      -e REAL_UID=$(id -u)
      -e REAL_GID=$(id -g)
      -v $PWD/build.sh:/build.sh
      -v $PWD:/src quay.io/pypa/manylinux1_x86_64
      /build.sh
    displayName: 'Wheel builds'
  
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: artifacts
      targetPath: dist/
    displayName: Publish artifacts
